# Generated by Django 5.1.2 on 2024-10-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemestercourse',
            name='registration_no',
            field=models.CharField(max_length=20),
        ),
    ]
